version: '3.9'
services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: kakeibo_user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: kakeibo_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile  # 本番用. 開発時はDockerfile.devを指定する
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=kakeibo_user
      - DB_PASSWORD=userpass
      - DB_NAME=kakeibo_db
      - JWT_SECRET=your_jwt_secret
      - GOOGLE_CLIENT_ID=xxxx.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=yyyy
    # 開発時は以下のvolumesでホットリロード
    volumes:
      - ./:/app

volumes:
  db_data:
