services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # ← 開発用に上書き
    volumes:
      - .:/app  # ソースコードをマウント
    ports:
      - "8080:8080"
    command: ["air", "-c", ".air.toml"]
